# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAzs7JGub6u7IHhJeXy_GiIQqQncEhWM
"""

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#total bill vs tip dataset(already exists in seaborn):

tips=sns.load_dataset('tips')

#first 5 rows
tips.head()

sns.set_theme()

#visualize the data
sns.relplot(data=tips,x='total_bill', y='tip',col='time',hue='smoker',style='smoker',size='size')

#load the iris dataset
iris=sns.load_dataset('iris')

iris.head()

"""scatter plot"""

sns.scatterplot(x='sepal_length',y='petal_length',hue='species',data=iris)

sns.scatterplot(x='sepal_length',y='petal_width',hue='species',data=iris)

#load the titanic dataset
titanic=sns.load_dataset('titanic')
titanic.head()

sns.countplot(x='class',data=titanic)

titanic.shape
sns.countplot(x='class',data=titanic)

sns.countplot(x='survived',data=titanic)

#bar chart
sns.barplot(x='sex',y='survived',hue='class', data=titanic)

#house price prediction

from sklearn.datasets import load_boston
house_boston=load_boston()